#!/usr/bin/env bash

set -e
# shellcheck disable=SC1091
. .venv/bin/activate
git pull
uv sync
m migrate
m collectstatic --noinput --clear
# m invalidate_cachalot
sudo systemctl restart emperor.uwsgi.service
