[build-system]
requires = ["uv_build>=0.9.7"]
build-backend = "uv_build"

[project]
authors = [
    {name = "Robert Huselius",email = "robert@huseli.us"}
]
description = ""
license = {text = "GPL-3.0-or-later"}
name = "podd-backend"
readme = "README.md"
requires-python = ">=3.11,<4.0"
version = "0.6.1"
dependencies = [
    "azure-identity",
    "azure-monitor-query",
    "django",
    "django-cachalot",
    "django-cors-headers",
    "django-extensions",
    "django-redis",
    "django-storages[azure]",
    "hiredis",
    "psycopg[binary]",
    "python-dotenv",
    "redis",
    "spodcat-backend",
    "whitenoise",
]

[dependency-groups]
dev = [
    "django-debug-toolbar",
    "flake8",
    "ipdb",
    "ipython",
    "isort",
    "pylint",
    "pylint-django",
    "spodcat-backend",
    "werkzeug>=3.1.8",
]

[project.scripts]
m = "podd_backend.manage:main"

[tool.uv]
exclude-newer = "P7D"

[tool.uv.sources]
spodcat-backend = { git = "https://github.com/Eboreg/spodcat-backend.git", branch = "v2" }

[tool.pylint.main]
disable = [
    "broad-exception-caught",
    "import-outside-toplevel",
    "invalid-name",
    "invalid-str-returned",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-positional-arguments",
    "too-many-return-statements",
    "too-many-statements",
]
ignore = [".venv", "node_modules"]
ignore-patterns = ["^\\.#", ".*\\.pyi", "apps\\.py"]
max-line-length = 119

[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
include_trailing_comma = true
line_length = 79
lines_after_imports = 2
multi_line_output = 3
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
skip = [".venv", "node_modules"]

[tool.mypy]
check_untyped_defs = true
files = "."
follow_imports = "skip"
ignore_missing_imports = true
show_error_codes = true

[[tool.mypy.overrides]]
ignore_errors = true
module = ["*.migrations.*"]

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".venv", ".git", ".mypy_cache", "__pycache__", "build", "node_modules", "scratch.py", "**/migrations"]
show-fixes = true

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E722", "B027"]

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = true
default-section = "third-party"
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.format]
quote-style = "double"
docstring-code-line-length = 80
