[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.9.7,<1.0.0"]

[project]
authors = [
    {name = "Robert Huselius",email = "robert@huseli.us"}
]
description = ""
license = {text = "GPL-3.0-or-later"}
name = "podd-backend"
readme = "README.md"
requires-python = ">=3.11,<4.0"
version = "0.7.0"
dependencies = [
    "azure-identity",
    "azure-monitor-query",
    "django",
    "django-cachalot",
    "django-cors-headers",
    "django-extensions",
    "django-redis",
    "django-storages[azure]",
    "hiredis",
    "psycopg[binary]",
    "python-dotenv",
    "redis",
    "spodcat-backend",
    "whitenoise",
]

[dependency-groups]
dev = [
    "django-debug-toolbar",
    "ipdb",
    "ipython",
    "ruff",
    "spodcat-backend",
    "werkzeug>=3.1.8",
]

[project.scripts]
m = "podd_backend.manage:main"

[tool.uv]
exclude-newer = "P7D"

[tool.uv.sources]
spodcat-backend = { git = "https://github.com/Eboreg/spodcat-backend.git", branch = "v2" }

[tool.ruff]
exclude = [".venv", ".git", ".mypy_cache", "__pycache__", "build", "node_modules", "scratch.py", "**/migrations"]
line-length = 120
show-fixes = true
target-version = "py312"

[tool.ruff.format]
docstring-code-line-length = 80
quote-style = "double"

[tool.ruff.lint]
ignore = ["E722", "B027"]
select = ["E", "F", "W", "B", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
default-section = "third-party"
lines-after-imports = 2
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
